name: AWS Scheduler Start

on:
  pull_request:
    branches:
      - master
  # schedule:
  #   - cron:  '0 1 * * 1-5' # UTC
  # workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-1

    - name: Fargate Start
      run: |
        aws application-autoscaling register-scalable-target --service-namespace ecs --scalable-dimension ecs:service:DesiredCount --min-capacity 1 --max-capacity 2 --resource-id service/app-dev-fargate-cluster/app-dev-bff
        aws application-autoscaling register-scalable-target --service-namespace ecs --scalable-dimension ecs:service:DesiredCount --min-capacity 1 --max-capacity 2 --resource-id service/app-dev-fargate-cluster/app-dev-rails
        aws application-autoscaling register-scalable-target --service-namespace ecs --scalable-dimension ecs:service:DesiredCount --min-capacity 1 --max-capacity 2 --resource-id service/app-dev-fargate-cluster/app-dev-api
        aws ecs update-service --cluster app-dev-fargate-cluster --service app-dev-sidekiq --desired-count 1

    - name: Aurora Start
      run: aws rds start-db-cluster --db-cluster-identifier app-dev
