name: Deploy

on:
  pull_request:
    branches:
      - master
      - develop

jobs:
  release-check:
    runs-on: ubuntu-latest
    outputs:
      label: ${{ steps.release-check.outputs.label }}
    steps:
    - id: release-check
      name: Check release label
      run: |
        LABEL=$(jq '[.pull_request.labels[].name][] | select(contains("release"))' $GITHUB_EVENT_PATH)
        echo $LABEL
        echo "::set-output name=label::$LABEL"

  deploy:
    needs: release-check
    runs-on: ubuntu-latest
    if: true && needs.release-check.outputs.label == 'release'

    steps:
    - name: Release
      run: echo 'Release'
