name: test

permissions:
  contents: read

on: 
  pull_request:

jobs:
  echo:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps: 
      - run: |
          echo '1' ${{ github.workflow }}
          echo '2' ${{ github.ref }}
          echo '3' ${{ github.head_ref }}
          echo '4' ${{ github.base_ref }}
