name: test

permissions:
  contents: read

on:
  workflow_dispatch:
    inputs:
      stage:
        required: true
        description: デプロイ先の環境名
        type: choice
        default: staging
        options:
          - production
          - staging

jobs:
  echo:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps: 
      - name:
        id: check
        run: |
          echo $GITHUB_REF_NAME
          echo ${{ inputs.stage }}
          if [ $GITHUB_REF_NAME = 'main' ] && [ ${{ inputs.stage }} = 'production' ]; then
            echo 'OK(production)'
            echo "STAGE=${{ inputs.stage }}" >> $GITHUB_ENV
          elif [ $GITHUB_REF_NAME = 'main' ] && [ ${{ inputs.stage }} = 'preview' ]; then
            echo 'OK(preview)'
            echo "STAGE=${{ inputs.stage }}" >> $GITHUB_ENV
          elif [ $GITHUB_REF_NAME = 'develop' ] && [ ${{ inputs.stage }} = 'staging' ]; then
            echo 'OK(staging)'
            echo "STAGE=${{ inputs.stage }}" >> $GITHUB_ENV
          else
            echo NG
            exit 1
          fi

      - name: print
        run: |
          echo ${{ inputs.stage }}
          echo ${{ env.STAGE }}
