name: test

permissions:
  contents: read

on:
  workflow_dispatch:
    inputs:
      branch:
        required: true
        description: ブランチ名
        type: choice
        default: main
        options:
          - main
          - develop
      stage:
        required: true
        description: デプロイ先の環境名
        type: choice
        default: staging
        options:
          - staging
          - production

jobs:
  echo:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps: 
      - run: |
          echo '1' ${{ inputs.branch }}
          echo '2' ${{ inputs.stage }}
