name: working directory test

permissions:
  contents: read

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    defaults:
      run:
        working-directory: work

    steps:
      - uses: actions/checkout@v3

      - name: check1
        shell: bash
        run: |
          pwd
          ls -l

      - uses: ./.github/actions/test
